services:
  backend:
    build: ./backend
    image: koop_backend
    container_name: koop-backend
    command:
      bash -c "chmod +x db_health_check.sh
      && ./db_health_check.sh
      && python manage.py collectstatic --noinput
      && python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/backend
      - static:/backend/static

  db:
    image: postgres:13
    container_name: koop-db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  static:
  db-data:
