# Generated by Django 3.2 on 2021-04-16 09:49

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(help_text='Link to the description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='coordinator',
            field=models.CharField(default='Emmy Noether', help_text='Name and surname of the week coordinator', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='pickup_date',
            field=models.DateField(default=datetime.date(2021, 4, 16), help_text='Wednesday when the orders are picked up', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.PositiveIntegerField(default=product.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product, unit', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='available quantity'),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.PositiveIntegerField(help_text='Week number of the year'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('number', 'year'), name='unique_week_number_in_year'),
        ),
        migrations.AddField(
            model_name='personalorder',
            name='pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.pickup'),
        ),
        migrations.AddField(
            model_name='personalorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalorder',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.week'),
        ),
        migrations.AddConstraint(
            model_name='personalorder',
            constraint=models.UniqueConstraint(fields=('user', 'week'), name='unique_user_order_per_week'),
        ),
        migrations.AddConstraint(
            model_name='personalorder',
            constraint=models.UniqueConstraint(fields=('week', 'pickup'), name='unique_pickup_per_week'),
        ),
    ]
