# Generated by Django 3.2 on 2021-04-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_create_personal_order_and_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='pickup',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Link to the description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product; unit', max_length=256),
        ),
    ]
