# Generated by Django 3.2 on 2021-04-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_small_adjustments_in_product_and_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalorder',
            name='pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_orders', to='product.pickup'),
        ),
        migrations.AlterField(
            model_name='personalorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalorder',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_orders', to='product.week'),
        ),
        migrations.AlterField(
            model_name='product',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.week'),
        ),
    ]
