# Generated by Django 3.2 on 2021-04-16 11:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_add_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPersonalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('personal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_personal_orders', to='product.personalorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_personal_orders', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='personalorder',
            name='products',
            field=models.ManyToManyField(related_name='personal_orders', through='product.ProductPersonalOrder', to='product.Product'),
        ),
    ]
