# Generated by Django 3.2 on 2021-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_add_product_personal_order_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productpersonalorder',
            constraint=models.UniqueConstraint(fields=('personal_order', 'product'), name='add_product_only_once_to_personal_order'),
        ),
    ]
